### ISSUE TITLE
Python 3 urlparse library Import error

### ISSUE THREAD

**Issue by nanorepublica** [founders4schools/django-donations#4]
where  `urlparse` is imported it should now be:

```
try:
    from urlparse import urlsplit, urlunsplit, parse_qs
except ImportError:
   from urllib.parse import urlsplit, urlunsplit, parse_qs
```

as per https://docs.python.org/3/library/urllib.parse.html

**Comment by browniebroke** [comment]
Or use six library to not screw up coverage... I want to get the tests to fail first, to make sure that's covered.

**Comment by developersf4s** [comment]
OK ;P
